language: go

service:
    docker

before_install:
    - git clone https://github.com/diodechain/cross-compile.git
    - cd cross-compile/pi-zero
    - docker image build -t crosscompile:0.1 .
    - cd ../..

script:
    - make test
    # test build on pi
    # - docker container run crosscompile:0.1 make
    - docker container run -v  "${PWD}:/build/diode_go_client" crosscompile:0.1 go build -tags openssl_static_pi

env:
  - GO111MODULE=on